#!/bin/bash
export VIRTUALENV_DIRECTORY='venv'

if [ ! -d "$VIRTUALENV_DIRECTORY" ]; then
    virtualenv $VIRTUALENV_DIRECTORY &&
    source $VIRTUALENV_DIRECTORY/bin/activate &&
    if [ "$1" = "dev" ]; then
       pip install -r requirements-dev.txt
    else
       pip install -r requirements.txt
    fi
else
    echo "[ERROR] Directory $VIRTUALENV_DIRECTORY already exists!"
fi
